---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.7'

inputs:
- name: bosh2-errand-resource-ci
- name: bosh2-errand-resource
  path: gopath/src/github.com/starkandwayne/bosh2-errand-resource

outputs:
- name: built-binaries

run:
  path: bosh2-errand-resource-ci/ci/tasks/build.sh
